name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: recursive  # Include git submodules (gjfpc-hook)
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20'
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '21'
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shfmt
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Run pre-commit test suite
      run: uv run python test/test_precommit.py
    - name: Upload test results on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-failure-logs
        path: |
          /tmp/pre-commit-test-*
        retention-days: 7
